# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zika Papers 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  crowdsourced open science project to organize and mine information from the scientific literature about the Zika fever and Zika virus 
baseurl: "/zika" # the subpath of your site, e.g. /blog
url: "http://pablomendes.github.io/zika" # the base hostname & protocol for your site
twitter_username: pablomendes
github_username:  pablomendes

# Build settings
markdown: kramdown
